[package]
name = "limechain-anchor-counter"
version = "0.1.0"
description = "Keypair-free Anchor compile sample for LimeChain Web3 Workstation"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "limechain_anchor_counter"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "=1.1.2"
