[features]
resolution = true
skip-lint = false

[programs.localnet]
limechain_anchor_counter = "7YT8qNhHFDUDJp56VUzxbZN5QFUz9VR4xhuYM6RywyDK"

[provider]
cluster = "Localnet"
wallet = "/dev/null"

[clients]
auto = false
